# Generated by Django 5.1.6 on 2025-02-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('executed', models.DecimalField(decimal_places=8, max_digits=20)),
                ('executed_coin', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_coin', models.CharField(max_length=10)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee_coin', models.CharField(max_length=10)),
            ],
        ),
    ]
